### ISSUE TITLE
Separate spaces for official and community docs

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hub/ACCESS-Hub#14]
The story:

As a user I want a clear distinction between documentation provided and supported by ACCESS-NRI, and documentation that is provided by the community.

As a member of the ACCESS-NRI I want it to be clear what documentation is supported by the NRI, so the community know where they can go if they have problems with NRI provided documentation.

A possible solution:

The [PR preview feature](https://github.com/ACCESS-NRI-Community/ACCESSHub/issues/11) shows that it is possible for two separate mkdocs sites to exist in their own subdirectory. This may be a solution to this issue: build and deploy the `main` branch to https://access-nri-community.github.io/ACCESSHub/Community and have another branch, `access-nri`, that deploys to https://access-nri-community.github.io/ACCESSHub/ACCESS-NRI.

Add some protection rules to the `access-nri` branch and that is a relatively simple solution. The `access-nri` branch can have different theme to differentiate it, and modified CI so that it deploys to the correct location.

**Comment by aidanheerdegen** [comment]
Pros for a separate branch and effectively separate mkdocs "sub-sites"
- Clearer identification of NRI vs Community supported documentation (Different colour scheme, Title)
- Each site can have it's own navigation tab structure, making more effective use of navigation hierarchy
- ACCESS-NRI content is effectively separated from the Community docs, less confusion and possibility to change NRI documentation with community PRs
- Search is local to each sub-site (only show documentation for NRI or Community)

Cons
- Search is local to each sub-site (don't show all possibly documentation, users might not realise search results will differ depending which sub-site they're on)

As one of the reasons to separate them is navigation, it is worth taking a bit of time to figure out what navigation would be desirable

Some possibilities:

NRI
```yaml
- Releases:
    - ACCESS-OM
    - ACCESS-AM
    - ACCESS-ESM
    - ACCESS-CM
- Models Components:
    - Land
    - Ocean
    - Ice
    - Atmosphere
    - Coupler
- Documentation and Training:
    - Technical
    - Analysis
    - Data
    - Policies
- Model Evaluation:
    - Tools
    - Tutorials
    - Background information
- Working Groups:
    - Ocean-Sea Ice (COSIMA)
    - Atmosphere
    - Coupled Models
    - Land
    - Technical
    - Next Generation Methods
- Community (link back to Community site)
```
```yaml
Community
- Modelling:
    - Ocean/Sea-Ice
    - ACCESS Coupled
    - ACCESS Seasonal
    - Land
    - Regional Atmosphere
    - Regional Ocean
    - Biogeochemistry
- Evaluation and Analysis:
   - CMIP
   - Land
   - Ocean Sea-ice
   - Atmosphere
   - Machine Learning
   - General
- Training resources:
   - General technical
   - Modelling
   - Analysis
- ACCESS-NRI Documentation
```
